### ISSUE TITLE
Add ability to run custom queries

### ISSUE THREAD

**Issue by kevinfodness** [alleyinteractive/elasticsearch-extensions#42]
# User Story

> As an implementer, I want to be able to run arbitrary queries against the search endpoint without having to hook into something that WP is doing or use plugin-specific logic.

# Acceptance Criteria

* Create a new method on the controller called `search` that accepts an array of DSL.
* When this method is invoked, it should trigger functionality on the adapters (SearchPress and VIP Enterprise Search) to run a query against their respective APIs and return results.
* Ensure there is a unit test to validate this functionality (ideally, build the solution test-driven).
* Update documentation in the wiki to add an entry for this functionality.

# Context

It would be nice to be able to run fully custom queries directly against Elasticsearch through the adapter (instead of through a search query, or ES_WP_Query) where DSL was provided instead of WP_Query-like arguments. There is a lot of power in Elasticsearch that can only be leveraged by writing Elasticsearch DSL and running the query directly, and having an ability to write and run custom queries would open up a lot of possibilities for end users.

Implementers should be able to access the functionality by doing something like the following:

```php
$results = elasticsearch_extensions()->search( $my_custom_query );
```

**Comment by renatonascalves** [comment]
See #44 (`VIP_Enterprise_Search:: query_post_suggestions`) for a place where this will be useful.

**Comment by renatonascalves** [comment]
I noticed, maybe, a problem with this approach. 

It requires the `https://github.com/elastic/elasticsearch` to be installed as well since the Spatie query builder requires it.

```
use Elasticsearch\Client;
use Spatie\ElasticsearchQueryBuilder\Builder;
use Spatie\ElasticsearchQueryBuilder\Queries\MatchQuery;
use Spatie\ElasticsearchQueryBuilder\Queries\MultiMatchQuery;

$client = Elasticsearch\ClientBuilder::create()->build();

$output = (new Builder($client))
  ->index("site-index")
  ->addQuery(
    MultiMatchQuery::create("group", ["name", "description"], fuzziness: "auto", type: 'best_fields')
  );

$output->search();
```

Also, its ES support is not that broad. The [multimatch](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-multi-match-query.html), for example, doesn't the `operator` param. I can easily see we would need to fill the gaps, specially since the idea here is to create custom ES queries.

**Comment by mboynes** [comment]
The DSL class should be all the API we need to build queries. Where it has gaps, we can fill it in over time. MVP for this issue is just to add a new abstract function to the `Adapter` class to query the ES endpoint directly. [ES_WP_Query](https://github.com/alleyinteractive/es-wp-query/blob/39c113e15fefb2a683b8e931fee9b5daf1ce921b/adapters/vip-search.php#L15-L32), [ES Admin](https://github.com/alleyinteractive/es-admin/blob/3141a169b771220c48a87902668c1ed5b8bca617/lib/adapters/class-adapter.php#L80-L89), and the [ES Toolkit](https://github.com/alleyinteractive/es-toolkit/blob/3f41d8dca0252071e08d3db4874ea30d42e45bfc/inc/adapters/interface-adapter.php#L41-L47) all provide similar functionality, so we have lots of prior art to port over.

**Comment by renatonascalves** [comment]
Putting it back into ready so that it is free for grab.

**Comment by jakewrfoster** [comment]
Needs feedback and testing: #72

**Comment by renatonascalves** [comment]
@jakewrfoster is it on purpose it doesn't handle or add support a custom or our DSL? Is it possible to use our DSL too? Could an example in the doc be provided?

**Comment by jakewrfoster** [comment]
@renatonascalves I'm not sure I follow the question. This support custom queries to be made. It is essentially a wrapper for the adapted services direct query functionality. No additional functionality is added beyond that.

I will write up an entry in the wiki in just a moment!

**Comment by jakewrfoster** [comment]
wiki entry added 👍
